apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    build: GUID-tasks
  name: GUID-tasks
spec:
  lookupPolicy:
    local: false
  tags:
  - name: 0.0-0
    from:
      kind: DockerImage
      name: image-registry.openshift-image-registry.svc:5000/GUID-tasks-dev/GUID-tasks:0.0-0
    importPolicy: {}
    referencePolicy:
      type: Source